apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment-via-argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example-container
        image: nginx
        ports:
        - containerPort: 8080
